# Generated by Django 3.2 on 2021-04-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_receipt',
            field=models.URLField(blank=True, default='', max_length=254),
        ),
    ]
