# Generated by Django 3.2 on 2021-04-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orignal_bag',
            new_name='original_bag',
        ),
    ]
