# Generated by Django 3.2 on 2021-04-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivary',
            name='packet_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='delivary',
            name='parcel_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
