# Generated by Django 3.2 on 2021-05-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210430_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
