# Generated by Django 3.2 on 2021-04-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_orderlineitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='lineitem_total',
            field=models.IntegerField(editable=False),
        ),
    ]
