# Generated by Django 3.2 on 2021-04-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='heading',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
