# Generated by Django 3.2 on 2021-05-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_paintings_scarfs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paintings',
            options={'verbose_name_plural': 'Paintings'},
        ),
        migrations.AlterModelOptions(
            name='scarfs',
            options={'verbose_name_plural': 'Scarfs'},
        ),
    ]
