# Generated by Django 3.2 on 2021-06-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='heading',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
