# Generated by Django 3.2 on 2021-06-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_privacypolicy_termsconditions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name_plural': 'Privacy Policy'},
        ),
        migrations.AlterModelOptions(
            name='termsconditions',
            options={'verbose_name_plural': 'Terms & Conditions'},
        ),
    ]
