# Generated by Django 3.2.4 on 2021-06-17 15:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210604_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('comment', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('update', models.DateTimeField()),
                ('site', models.CharField(max_length=250)),
            ],
        ),
    ]
