# Generated by Django 3.2 on 2021-04-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feat_item',
            field=models.BooleanField(default=False),
        ),
    ]
